apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-circle-service
  labels:
    app: vote-circle-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-circle-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: vote-circle-service
    spec:
      containers:
        - name: vote-circle-service
          image: registry.digitalocean.com/vyf/vote-your-face/service-vote_circle:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: production
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: vote-circle-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: vote-circle-service