# web service
port: 8080
circle:
  maxAmountPerUser: 10
  maxVoters: 100

# hosts
hosts:
  vec: http://localhost:4200/
  svc:
    sso: http://localhost:1010

# aws
aws:
  auth:
    clientId: clientId
    userPoolId: poolId
    awsDefaultRegion: eu-central-1
    clientSecret: secret
  s3:
    accessKeyId: keyId
    accessKeySecret: secret
    region: eu-central-1
    bucketName: bucket
    uploadTimeout: 100
    defaultBaseURL: url

# Database
db:
  host: publicPostgresDb
  port: 5432
  name: name
  user: user
  password: pwd
  test:
    host: db
    port: 5432
    name: tname
    user: user
    password: pwd

# Redis server
redis:
  host: public-redis-1
  port: 6379
  username: default
  db: 1
  timeout: 60
  password: pwd

# ably service
ably:
  apikey: key
  clientId: vote-circle-service

# Security
security:
  secrets:
    key: secret

# used token definitions
token:
  type: bearer
