# logger configuration
zap_config:
  level: "debug"
  encoding: "console"
  development: true
  encoderConfig:
    messageKey: "Msg"
    levelKey: "Level"
    timeKey: "Time"
    nameKey: "Name"
    callerKey: "Caller"
    stacktraceKey: "St"
    levelEncoder: "capital"
    timeEncoder: "iso8601"
    durationEncoder: "string"
    callerEncoder: "short"
  outputPaths:
    - "stdout"
    # - "./application.log"
  errorOutputPaths:
    - "stdout"
    # - "./error.log"

log_rotate:
  maxsize: 3
  maxage: 7
  maxbackups: 7